
if_stmt -> 'IF' expression 'THEM' stmt_section _elsif* _else? 'END_IF' ';'
	 ;

_elsif -> 'ELSIF' expression 'THEN' stmt_section
	;

_else -> 'ELSE' stmt_section
       ;

case_stmt -> 'CASE' (variable | expression) 'OF' _case_value+ _else? 'END_CASE' ';'
	   ;

_case_value -> value_list ':' stmt_section
	     ;

value_list -> _value_list_value (',' _value_list_value)*
	    ;

_value_list_value -> constant ('..' constant)?
		   ;

rept_and_jump_stmt -> for_stmt
		    | while_stmt
		    | repeat_stmt
		    | exit_stmt
		    | return_stmt
		    | waitforcondition_stmt
		    | goto_stmt
		    ;

goto_stmt -> 'GOTO' jump_label ';'
	   ;      

exit_stmt -> 'EXIT' ';'
	   ;

return_stmt -> 'RETURN' ';'
	     ;

waitforcondition_stmt -> 'WAITFORCONDITION' expression_identifier _params? _with? 'DO' stmt_section 'END_WAITFORCONDITION' ';'
		       ;

repeat_stmt -> 'REPEAT' stmt_section 'UNTIL' expression 'END_REPEAT' ';'
	     ;

while_stmt -> 'WHILE' expression 'DO' stmt_section 'END_WHILE' ';'
	    ;

for_stmt -> 'FOR' variable_identifier _start_value? 'TO' expression _by_expression? 'DO' stmt_section 'END_FOR' ';'
	  ;

_start_value -> ':=' expression
	      ;

_by_expression -> 'BY' expression
		;

_params -> '(' fc_parameter ')'
	 ;

_with -> 'WITH' expression
       ;

       
